### ISSUE TITLE
Optimize scraping by checking if data doesn't change

### ISSUE THREAD

**Issue by angeloanan** [angeloanan/kominfo-d-#16]
The endpoint for the API provides you with the count of data

We can utilize that and stop unneeded fetch from happenning.

**Comment by rogojagad** [comment]
Selamat siang Mas @angeloanan mau konfirmasi untuk scope issue ini.

Jadi intinya kita hanya melakukan scrapping data yg belum ada saja ya? bedasarkan field `total` yang ada di response API.

Misal:
1. untuk data PSE Asing tercatat kita punya 8721 data, dari response API tertulis total data adalah 8721, maka ekspektasinya kita tidak perlu melakukan scrapping.
2. untuk data PSE Asing tercatat kita punya 8721 data, tetapi dari response API tertulis total data adalah 8730, maka ekspektasinya kita hanya perlu melakukan scrapping untuk 9 data yang belum ada saja.

Benar begitu bukan ya mas? Terima kasih.

Kalau benar begitu, saya berminat untuk contribute improvement untuk issue ini. Terima kasih mas :-)

**Comment by angeloanan** [comment]
Yes, plan nya mirip begitu.

Disini, hasil scraping saya itu langsung menggabungkan data PSE Lokal dengan data PSE Global ke `public/data.json`. Saya berpikiran, bagaimana jika kita waktu scraping, kita test apakah datanya sudah ada atau belum. Jika belum, ditambahkan ke data; Jika sudah, berhenti scraping.

Cuma, dipikir kembali, ada edge case, dimana mungkin ada PSE yang statusnya berubah menjadi "dihentikan sementara", dan datanya langsung hilang dari database yang diterbitkan (Lihat https://twitter.com/AfterDarkAngelo/status/1553200439759601664).

Jadi, mungkin hal ini harus dimatangkan terlebih dahulu flow scrapingnya bagaimana.

Jika mas masih mau coba untuk solve issue ini, silahkan, saya akan assign issue ke mas, ya 👍

**Comment by rogojagad** [comment]
Noted mas. Brrti ada case dimana data akan hilang ya.

Sepertinya boleh juga saya coba untuk solve issue ini. Boleh mas jika mau diassign.

Terimakasih.

**Comment by alan1420** [comment]
Atau bisa dengan scrape div element pada halaman Daftar PSE Domestik/Asing yang isinya "data terbaru per tanggal 30 Juli 2022 Pukul 07:59"

**Comment by angeloanan** [comment]
Oh wow I've completely missed that. If so then tinggal cek apakah div itu terganti atau gak. Kalau terganti, scrape, kalo ga, gaperlu.

Great catch!

**Comment by rogojagad** [comment]
nice info @alan1420 

iya nih sepertinya bisa dipake buat pengecekan kalau tanggal + jam nya gak keupdate, gaperlu scrap.

**Comment by rogojagad** [comment]
update:

sepertinya kita bisa utilize endpoint ini https://pse.kominfo.go.id/static/json-static/generationInfo.json

instead of kita harus scrap halaman list PSE nya karena untuk scrap halaman itu aku cek harus pake headless browser.

**Comment by rogojagad** [comment]
saya sudah open PR untuk issue ini, mohon bantuannya untuk dicek ya mas @angeloanan 

terima kasih

**Comment by alan1420** [comment]
@angeloanan aku ada saran nih, gimana kalau timestamp dari generate datanya ditampilkan ke front end juga

**Comment by rogojagad** [comment]
kayaknya oke juga tuh @alan1420 @angeloanan
