### ISSUE TITLE
[SUGGESTION] Use Kominfo's TrustPositif API

### ISSUE THREAD

**Issue by rorre** [angeloanan/kominfo-d-#20]
Merely a suggestion, but it seems like you can just input the web's domain.tld into [Kominfo's TrustPositif form](https://trustpositif.kominfo.go.id/) to check if its blocked or not.

That method could be more reliable than checking to `indi.wtf` (tho i guess checking from both sources wouldn't hurt)

**Comment by angeloanan** [comment]
Will keep in mind. Thank you for the suggestion!

**Comment by Meta502** [comment]
Might take up this issue if no one is implementing it currently, any guidelines for contributing or should i just fork and pull? @angeloanan
