### ISSUE TITLE
Is it true that Godot engine is blocked?

### ISSUE THREAD

**Issue by qrhfz** [angeloanan/kominfo-d-#32]
Or is it just godot's website is down?

**Comment by alan1420** [comment]
Lagi down sepertinya

**Comment by hahn** [comment]
halaman docsnya sih bisa https://docs.godotengine.org/en/stable/

**Comment by angeloanan** [comment]
It looks like their website is down (https://godotengine.org/). Please ignore the error that's happening currently in the website.
