### ISSUE TITLE
I think the logic here is flawed

### ISSUE THREAD

**Issue by castrix** [angeloanan/kominfo-d-#7]
I just read the source code and I noticed that your logic [here](https://github.com/angeloanan/kominfo-d-/blob/main/src/pages/index.tsx) is comparing the hardcoded [website data](https://github.com/angeloanan/kominfo-d-/blob/main/src/_data/websites.ts) to the response from the `api`.

My concern is that, how do you know if [these websites](https://github.com/angeloanan/kominfo-d-/blob/main/src/_data/websites.ts) **must register** their app and services while the logic [here](https://github.com/angeloanan/kominfo-d-/blob/main/src/pages/index.tsx) is only checking if the website is listed/exist in the goverment or not?

For the example, how do you know if `github`, `bitbucket` & `npm` **must** register their services? And how do you know that those sites will be blocked if they didn't register to the goverment?

I think this logic can make the confusion and unrest to the user. Instead I suggest you to only show the `pass` existing sites, or you change the wording `blocked` to something like `unregistered` and add the `disclaimer` about what those status means.

**Comment by angeloanan** [comment]
Hello, thanks for your concern!

Before I start, I'm going to declare that I am not a lawyer and I have not talked with any lawyer regarding the ruling.

Pada [Permenkominfo 5/2020](https://peraturan.bpk.go.id/Home/Details/203049/permenkominfo-no-5-tahun-2020) Bab 1 Pasal 1 Nomor 5 dan 6, terdefinisikan bahwa:

> 5. **Penyelenggara Sistem Elektronik** adalah setiap orang, penyelenggara negara, badan usaha, dan masyarakat yang menyediakan, mengelola, dan/atau mengoperasikan Sistem Elektronik secara sendiri-sendiri maupun bersama-sama kepada Pengguna Sistem Elektronik untuk keperluan dirinya dan/atau keperluan pihak lain. 
> 6. **Penyelenggara Sistem Elektronik Lingkup Privat** yang selanjutnya disebut **PSE Lingkup Privat** adalah penyelenggaraan Sistem Elektronik oleh orang, badan usaha, dan masyarakat.

dan juga, pada Permenkominfo 5/2020 Bab II Pasal 2 Nomor 1 dan 2 menyatakan bahwa:

> 1. Setiap PSE Lingkup Privat **wajib** melakukan pendaftaran.
> 2. PSE Lingkup Privat sebagaimana dimaksud pada ayat (1) meliputi:
>   a. Penyelenggara Sistem Elektronik yang diatur atau diawasi oleh Kementerian atau Lembaga berdasarkan ketentuan peraturan perundangundangan; dan/atau
>   b. Penyelenggara Sistem Elektronik yang memiliki portal, situs, atau aplikasi dalam jaringan melalui internet yang dipergunakan untuk:
>     1. **menyediakan, mengelola, dan/atau mengoperasikan penawaran dan/atau perdagangan barang dan/atau jasa**;
>     2. menyediakan, mengelola, dan/atau mengoperasikan layanan transaksi keuangan;
>     3. pengiriman materi atau muatan digital berbayar melalui jaringan data baik dengan cara unduh melalui portal atau situs, pengiriman lewat surat elektronik, atau melalui aplikasi lain ke perangkat Pengguna Sistem Elektronik;
>     4. menyediakan, mengelola, dan/atau mengoperasikan layanan komunikasi meliputi namun tidak terbatas pada pesan singkat, panggilan suara, panggilan video, surat elektronik, dan percakapan dalam jaringan dalam bentuk platform digital, layanan jejaring dan media sosial;
>     5. layanan mesin pencari, layanan penyediaan Informasi Elektronik yang berbentuk tulisan, suara, gambar, animasi, musik, video, film, dan permainan atau kombinasi dari sebagian dan/ atau seluruhnya; dan/atau
>     6. pemrosesan Data Pribadi untuk kegiatan operasional melayani masyarakat yang terkait dengan aktivitas Transaksi Elektronik. 

Pada Permenkominfo 5/2020 Bab II Pasal 2 Nomor 2b bulir 1 (bolded), cakupan definisi ini terlalu luas. Secara teoritis, GitHub, BitBucket dan NPM menawarkan jasa, yaitu menyimpan source code dari libraries yang dibutuhkan. Juga, secara teoritis, definisi `jasa` ini dapat dimainkan supaya bisa berarti `memberikan informasi`. Sebagai contoh, menurut mu, apakah [KBBI Daring Kemdikbud](https://kbbi.kemdikbud.go.id) memberikan jasa (ya saya tahu ini bukan PSE Lingkup Privat, hanya contoh)? Secara teoritis, mereka juga memberikan jasa yaitu memberi definisi (informasi) dari kata yang ada dalam Bahasa Indonesia.

---

Pada Permenkominfo 5/2020 Bab II Bagian ketiga Pasal 7 Nomor 2 dinyatakan bahwa:

> 2. Dalam hal PSE Lingkup Privat tidak melakukan pendaftaran sebagaimana dimaksud pada ayat (1) huruf a, Menteri memberikan sanksi administratif berupa Pemutusan Akses terhadap Sistem Elektronik (access blocking).

Disini, saya merasa penggunaan kata `Blocked` pada situs ini akurat.

Once again, the point of this app is to highlight the most common services / app that Indonesians uses and to highlight what will be missing if the said `PSE Lingkup Privat` did not register themselves to the government.

**Comment by angeloanan** [comment]
As I believe that this is a non-issue, I'm going to close this.

Feel free to follow up if you have more questions / leads!
